# Generated by Django 4.2 on 2025-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام افزونه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('active', models.BooleanField(default=False, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'افزونه',
                'verbose_name_plural': 'افزونه\u200cها',
            },
        ),
    ]
