# Generated by Django 4.2 on 2025-05-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('successful', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه تراکنش')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آی\u200cدی پی'), ('internal', 'داخلی')], default='zarinpal', max_length=100, verbose_name='درگاه پرداخت')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='آدرس بازگشت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('payment_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('successful', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد مرجع تراکنش')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='پاسخ درگاه')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('payment_method', models.CharField(max_length=100, verbose_name='روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش')),
                ('is_paid', models.BooleanField(default=True, verbose_name='پرداخت شده')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='ست\u200cبند/طراح')),
            ],
            options={
                'verbose_name': 'پرداخت به طراح',
                'verbose_name_plural': 'پرداخت\u200cهای طراحان',
                'ordering': ['-payment_date'],
            },
        ),
    ]
