# Generated by Django 4.2 on 2025-05-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('set_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerpayment',
            name='set_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='set_design.setdesign', verbose_name='ست\u200cبندی مرتبط'),
        ),
    ]
