# Generated by Django 4.2 on 2025-06-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhysicalStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('stamp_type', models.CharField(choices=[('wood', 'مهر چوبی'), ('laser', 'حکاکی لیزری')], max_length=20, verbose_name='نوع مهر')),
                ('dimensions', models.CharField(max_length=100, verbose_name='ابعاد درخواستی')),
                ('material', models.CharField(max_length=100, verbose_name='جنس درخواستی')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('in_progress', 'در حال ساخت'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی تکمیل')),
                ('actual_completion', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل واقعی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_craft_stamp_requests', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_stamp_requests', to='business.business', verbose_name='کسب\u200cوکار')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='craft_stamp_requests', to='designs.design', verbose_name='طرح')),
            ],
            options={
                'verbose_name': 'درخواست مهر فیزیکی',
                'verbose_name_plural': 'درخواست\u200cهای مهر فیزیکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام مهر')),
                ('stamp_type', models.CharField(choices=[('wood', 'مهر چوبی'), ('laser', 'حکاکی لیزری')], max_length=20, verbose_name='نوع مهر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('damaged', 'آسیب دیده'), ('retired', 'بازنشسته')], default='active', max_length=20, verbose_name='وضعیت')),
                ('dimensions', models.CharField(max_length=100, verbose_name='ابعاد')),
                ('material', models.CharField(max_length=100, verbose_name='جنس')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ساخت')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخرین استفاده')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craft_physical_stamps', to='business.business', verbose_name='کسب\u200cوکار')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='craft_physical_stamps', to='designs.design', verbose_name='طرح')),
            ],
            options={
                'verbose_name': 'مهر فیزیکی',
                'verbose_name_plural': 'مهرهای فیزیکی',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
