# Generated by Django 4.2 on 2025-05-03 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('business', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مناقصه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('tender_type', models.CharField(choices=[('design', 'طراحی'), ('print', 'چاپ'), ('both', 'طراحی و چاپ')], max_length=20, verbose_name='نوع مناقصه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز'), ('in_progress', 'در حال بررسی'), ('awarded', 'برنده\u200cدار شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('deadline', models.DateTimeField(verbose_name='مهلت ارسال پیشنهاد')),
                ('budget_min', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل بودجه (ریال)')),
                ('budget_max', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر بودجه (ریال)')),
                ('required_design_count', models.PositiveIntegerField(default=1, verbose_name='تعداد طرح مورد نیاز')),
                ('required_print_count', models.PositiveIntegerField(default=0, verbose_name='تعداد چاپ مورد نیاز')),
                ('requirements', models.TextField(blank=True, verbose_name='الزامات فنی')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tenders/attachments/', verbose_name='فایل\u200cهای پیوست')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tenders', to='authentication.user', verbose_name='ایجاد کننده')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='business.business', verbose_name='برنده مناقصه')),
            ],
            options={
                'verbose_name': 'مناقصه',
                'verbose_name_plural': 'مناقصه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('proposed_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پیشنهادی (ریال)')),
                ('description', models.TextField(verbose_name='توضیحات پیشنهاد')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='زمان تحویل (روز)')),
                ('status', models.CharField(choices=[('submitted', 'ارسال شده'), ('under_review', 'در حال بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='tender_bids/attachments/', verbose_name='فایل\u200cهای پیوست')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_bids', to='business.business', verbose_name='کسب\u200cوکار')),
                ('proposed_designs', models.ManyToManyField(blank=True, related_name='tender_bids', to='designs.design', verbose_name='طرح\u200cهای پیشنهادی')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tender.tender', verbose_name='مناقصه')),
            ],
            options={
                'verbose_name': 'پیشنهاد مناقصه',
                'verbose_name_plural': 'پیشنهادهای مناقصه',
                'ordering': ['-created_at'],
                'unique_together': {('tender', 'business')},
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tender', to='tender.tenderbid', verbose_name='پیشنهاد برنده'),
        ),
    ]
