# Generated by Django 4.2 on 2025-06-11 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '__first__'),
        ('designs', '__first__'),
        ('print_locations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض لباس (cm)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع لباس (cm)')),
                ('garment_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('custom', 'سفارشی')], max_length=10, null=True, verbose_name='اندازه لباس')),
                ('custom_size_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات سایز سفارشی')),
                ('fabric_type', models.CharField(blank=True, max_length=50, verbose_name='نوع پارچه')),
                ('fabric_color', models.CharField(blank=True, max_length=50, verbose_name='رنگ پارچه')),
                ('fabric_material', models.CharField(blank=True, max_length=50, verbose_name='جنس پارچه')),
                ('fabric_weight', models.PositiveIntegerField(blank=True, help_text='گرم بر متر مربع', null=True, verbose_name='وزن پارچه')),
                ('fabric_details', models.TextField(blank=True, verbose_name='توضیحات اضافی پارچه')),
                ('print_option', models.CharField(choices=[('manual', 'دستی'), ('digital', 'دیجیتال'), ('screen', 'سیلک اسکرین'), ('embroidery', 'گلدوزی'), ('heat_transfer', 'پرس حرارتی')], default='manual', max_length=15, verbose_name='گزینه چاپ')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت کل (ریال)')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پیش\u200cپرداخت (ریال)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای مشتری')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای داخلی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای عمومی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='سایز')),
                ('fabric', models.CharField(choices=[('cotton', 'پنبه'), ('polyester', 'پلی\u200cاستر'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع پارچه')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ لباس')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('print_type', models.CharField(choices=[('screen', 'چاپ سیلک'), ('digital', 'چاپ دیجیتال'), ('sublimation', 'چاپ سابلیمیشن'), ('embroidery', 'گلدوزی')], max_length=20, verbose_name='نوع چاپ')),
                ('has_rakab', models.BooleanField(default=False, verbose_name='دارای رکب')),
                ('rakab_type', models.CharField(blank=True, max_length=50, verbose_name='نوع رکب')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت کل (ریال)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order', verbose_name='سفارش')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='designs.template', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش',
                'verbose_name_plural': 'جزئیات سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PrintProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('design', 'طراحی'), ('prepress', 'پیش\u200cچاپ'), ('printing', 'چاپ'), ('postpress', 'پس\u200cچاپ'), ('quality_control', 'کنترل کیفیت'), ('packaging', 'بسته\u200cبندی')], default='design', max_length=50, null=True, verbose_name='مرحله')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('business_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_processes', to='business.business', verbose_name='مجری مسئول')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_processes', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فرآیند چاپ',
                'verbose_name_plural': 'فرآیندهای چاپ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سفارش',
                'verbose_name_plural': 'تاریخچه وضعیت سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('stage_type', models.CharField(choices=[('order_received', 'دریافت سفارش'), ('design_approval', 'تأیید طرح'), ('set_design', 'ست\u200cبندی'), ('printing_prep', 'آماده\u200cسازی چاپ'), ('printing', 'چاپ'), ('quality_check', 'کنترل کیفیت'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال'), ('delivered', 'تحویل')], max_length=20, verbose_name='نوع مرحله')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در جریان'), ('completed', 'تکمیل شده'), ('on_hold', 'متوقف'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرحله سفارش',
                'verbose_name_plural': 'مراحل سفارش',
                'ordering': ['order', 'stage_type'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('color_count', models.PositiveIntegerField(default=1, verbose_name='تعداد رنگ')),
                ('print_dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد چاپ')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت کل (ریال)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='designs.design', verbose_name='طرح')),
                ('order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderdetail', verbose_name='جزئیات سفارش')),
                ('print_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='print_locations.printlocation', verbose_name='محل چاپ')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarmentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول (سانتی\u200cمتر)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض (سانتی\u200cمتر)')),
                ('sleeve_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول آستین (سانتی\u200cمتر)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور سینه (سانتی\u200cمتر)')),
                ('shoulder_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض شانه (سانتی\u200cمتر)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای اندازه\u200cگیری')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garment_details', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'جزئیات لباس',
                'verbose_name_plural': 'جزئیات لباس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('is_inner_print', models.BooleanField(default=False, verbose_name='رکب به داخل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد تکرار')),
                ('custom_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)')),
                ('custom_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)')),
                ('special_instructions', models.TextField(blank=True, verbose_name='دستورات ویژه')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sections', to='designs.design', verbose_name='طرح')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sections', to='designs.printlocation', verbose_name='محل چاپ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'بخش سفارش',
                'verbose_name_plural': 'بخش\u200cهای سفارش',
                'unique_together': {('order', 'location', 'design')},
            },
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('print', 'چاپ'), ('set', 'ست\u200cبندی'), ('delivery', 'تحویل')], max_length=20, verbose_name='نوع فرآیند')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (ریال)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت انجام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_assignments', to='business.business', verbose_name='کسب\u200cوکار')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تکلیف سفارش',
                'verbose_name_plural': 'تکلیف\u200cهای سفارش',
                'unique_together': {('order', 'business', 'process_type')},
            },
        ),
    ]
