# Generated by Django 4.2 on 2025-05-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('business', '0001_initial'),
        ('print_locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('garment_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('custom', 'سفارشی')], max_length=20, null=True, verbose_name='سایز لباس')),
                ('custom_size_details', models.JSONField(blank=True, null=True, verbose_name='جزئیات سایز سفارشی')),
                ('fabric_type', models.CharField(blank=True, choices=[('cotton', 'پنبه'), ('polyester', 'پلی\u200cاستر'), ('cotton_polyester', 'پنبه-پلی\u200cاستر'), ('silk', 'ابریشم'), ('other', 'سایر')], max_length=20, null=True, verbose_name='نوع پارچه')),
                ('fabric_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ پارچه')),
                ('fabric_weight', models.PositiveIntegerField(blank=True, help_text='گرم بر متر مربع', null=True, verbose_name='وزن پارچه')),
                ('fabric_details', models.TextField(blank=True, verbose_name='توضیحات اضافی پارچه')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت کل (ریال)')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پیش\u200cپرداخت (ریال)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('customer_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای مشتری')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای داخلی')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت واحد (ریال)')),
                ('print_dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد چاپ')),
                ('color_count', models.PositiveIntegerField(default=1, verbose_name='تعداد رنگ')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='designs.design', verbose_name='طرح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('print_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='print_locations.printlocation', verbose_name='محل چاپ')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['order', 'id'],
            },
        ),
    ]
