# Generated by Django 4.2 on 2025-06-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '__first__'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='print_location',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rakeb_orientation',
            field=models.CharField(choices=[('inside', 'به داخل'), ('outside', 'به بیرون')], default='outside', max_length=7, verbose_name='رکب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='clothing.clothingsection', verbose_name='بخش لباس'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
