# Generated by Django 4.2 on 2025-06-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_printlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fabric_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس پارچه'),
        ),
        migrations.AddField(
            model_name='order',
            name='print_type',
            field=models.CharField(blank=True, choices=[('manual', 'دستی'), ('digital', 'دیجیتال'), ('screen', 'سیلک اسکرین'), ('embroidery', 'گلدوزی'), ('heat_transfer', 'انتقال حرارتی')], default='manual', max_length=15, null=True, verbose_name='نوع چاپ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_type',
            field=models.CharField(blank=True, choices=[('cotton', 'پنبه'), ('polyester', 'پلی\u200cاستر'), ('cotton_polyester', 'پنبه-پلی\u200cاستر'), ('lycra', 'لایکرا'), ('silk', 'ابریشم'), ('linen', 'کتان')], max_length=20, null=True, verbose_name='نوع پارچه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='garment_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('custom', 'سفارشی')], max_length=10, null=True, verbose_name='اندازه لباس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('set_design', 'در مرحله ست\u200cبندی'), ('printing', 'در حال چاپ'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('stage_type', models.CharField(choices=[('order_received', 'دریافت سفارش'), ('design_approval', 'تأیید طرح'), ('set_design', 'ست\u200cبندی'), ('printing_prep', 'آماده\u200cسازی چاپ'), ('printing', 'چاپ'), ('quality_check', 'کنترل کیفیت'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال'), ('delivered', 'تحویل')], max_length=20, verbose_name='نوع مرحله')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در جریان'), ('completed', 'تکمیل شده'), ('on_hold', 'متوقف'), ('cancelled', 'لغو شده')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرحله سفارش',
                'verbose_name_plural': 'مراحل سفارش',
                'ordering': ['order', 'stage_type'],
            },
        ),
        migrations.CreateModel(
            name='GarmentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول (سانتی\u200cمتر)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض (سانتی\u200cمتر)')),
                ('sleeve_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='طول آستین (سانتی\u200cمتر)')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='دور سینه (سانتی\u200cمتر)')),
                ('shoulder_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض شانه (سانتی\u200cمتر)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای اندازه\u200cگیری')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garment_details', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'جزئیات لباس',
                'verbose_name_plural': 'جزئیات لباس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_inner_print', models.BooleanField(default=False, verbose_name='رکب به داخل')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد تکرار')),
                ('custom_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)')),
                ('custom_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)')),
                ('special_instructions', models.TextField(blank=True, verbose_name='دستورات ویژه')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sections', to='designs.design', verbose_name='طرح')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_sections', to='designs.printlocation', verbose_name='محل چاپ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'بخش سفارش',
                'verbose_name_plural': 'بخش\u200cهای سفارش',
                'unique_together': {('order', 'location', 'design')},
            },
        ),
    ]
