# Generated by Django 4.2 on 2025-06-09 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessactivity_activity_type_and_more'),
        ('print_locations', '0002_alter_printlocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0005_template'),
        ('orders', '0003_order_fabric_material_order_print_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='color_count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='print_dimensions',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت کل (ریال)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='print_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='print_locations.printlocation', verbose_name='محل چاپ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد (ریال)'),
        ),
        migrations.CreateModel(
            name='PrintProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('print_file', models.FileField(blank=True, null=True, upload_to='prints/', verbose_name='فایل چاپ')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='print_previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_processes', to='business.business', verbose_name='کسب\u200cوکار چاپ')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_processes', to='orders.orderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'فرآیند چاپ',
                'verbose_name_plural': 'فرآیندهای چاپ',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('set_design', 'در مرحله ست\u200cبندی'), ('printing', 'در حال چاپ'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت سفارش',
                'verbose_name_plural': 'تاریخچه وضعیت سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, verbose_name='سایز')),
                ('fabric', models.CharField(choices=[('cotton', 'پنبه'), ('polyester', 'پلی\u200cاستر'), ('mixed', 'مختلط')], max_length=20, verbose_name='نوع پارچه')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ لباس')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('print_type', models.CharField(choices=[('screen', 'چاپ سیلک'), ('digital', 'چاپ دیجیتال'), ('sublimation', 'چاپ سابلیمیشن'), ('embroidery', 'گلدوزی')], max_length=20, verbose_name='نوع چاپ')),
                ('has_rakab', models.BooleanField(default=False, verbose_name='دارای رکب')),
                ('rakab_type', models.CharField(blank=True, max_length=50, verbose_name='نوع رکب')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد (ریال)')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت کل (ریال)')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order', verbose_name='سفارش')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='designs.template', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'جزئیات سفارش',
                'verbose_name_plural': 'جزئیات سفارش\u200cها',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderdetail', verbose_name='جزئیات سفارش'),
        ),
        migrations.CreateModel(
            name='OrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('print', 'چاپ'), ('set', 'ست\u200cبندی'), ('delivery', 'تحویل')], max_length=20, verbose_name='نوع فرآیند')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (ریال)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت انجام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_assignments', to='business.business', verbose_name='کسب\u200cوکار')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تکلیف سفارش',
                'verbose_name_plural': 'تکلیف\u200cهای سفارش',
                'unique_together': {('order', 'business', 'process_type')},
            },
        ),
    ]
