# Generated by Django 4.2 on 2025-06-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_options_remove_orderitem_color_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد رنگ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='print_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد چاپ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
