# Generated by Django 4.2 on 2025-06-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_role_permissions_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='authentication.role', verbose_name='نقش\u200cها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='authentication.role', verbose_name='نقش فعلی'),
        ),
    ]
