# Generated by Django 4.2 on 2025-05-03 20:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی طرح',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای طرح',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام خانواده')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(blank=True, related_name='families', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'خانواده',
                'verbose_name_plural': 'خانواده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyDesignRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(max_length=100, verbose_name='نوع طرح')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_required', models.BooleanField(default=True, verbose_name='ضروری است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requirements', to='designs.family', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'نیاز طراحی خانواده',
                'verbose_name_plural': 'نیازهای طراحی خانواده\u200cها',
                'ordering': ['family', 'design_type'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='families', to='designs.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان طرح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(blank=True, null=True, upload_to='designs/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'ai', 'eps', 'pdf'])], verbose_name='فایل اصلی')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='designs/previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (ریال)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('categories', models.ManyToManyField(related_name='designs', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL, verbose_name='طراح')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_families', to='designs.design', verbose_name='طرح')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_families', to='designs.family', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'طرح-خانواده',
                'verbose_name_plural': 'طرح\u200cهای-خانواده\u200cها',
                'ordering': ['family', 'position'],
                'unique_together': {('design', 'family')},
            },
        ),
    ]
