# Generated by Django 4.2 on 2025-06-11 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان طرح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('design_type', models.CharField(choices=[('vector', 'وکتوری'), ('image', 'عکس'), ('combined', 'ترکیبی')], default='vector', max_length=20, verbose_name='نوع طرح')),
                ('vector_file', models.FileField(blank=True, null=True, upload_to='designs/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'ai', 'eps', 'pdf'])], verbose_name='فایل وکتور')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='designs/images/', verbose_name='تصویر محصول')),
                ('laser_file', models.FileField(blank=True, null=True, upload_to='designs/laser/', verbose_name='فایل مخصوص لیزر')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض (پیکسل)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع (پیکسل)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (ریال)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
            ],
            options={
                'verbose_name': 'طرح',
                'verbose_name_plural': 'طرح\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی طرح',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای طرح',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام خانواده')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('required_design_types', models.JSONField(default=dict, help_text='نوع و تعداد طرح\u200cهای مورد نیاز برای این خانواده', verbose_name='نیازمندی\u200cهای طرح')),
                ('exclusive_design_types', models.JSONField(default=list, help_text='انواع طرح\u200cهایی که فقط مختص این خانواده هستند', verbose_name='انواع طرح\u200cهای انحصاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('categories', models.ManyToManyField(blank=True, related_name='families', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'خانواده',
                'verbose_name_plural': 'خانواده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام مهر')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مهر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('in_use', 'در حال استفاده'), ('maintenance', 'در تعمیر'), ('retired', 'بازنشسته')], default='available', max_length=50, verbose_name='وضعیت')),
                ('size', models.CharField(max_length=100, verbose_name='اندازه')),
                ('material', models.CharField(max_length=100, verbose_name='جنس')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخرین تعمیر')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='تعمیر بعدی')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد استفاده')),
                ('location', models.CharField(max_length=255, verbose_name='محل نگهداری')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name='تصویر مهر')),
                ('laser_file', models.FileField(blank=True, null=True, upload_to='stamps/laser/', verbose_name='فایل لیزری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_stamps', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
            ],
            options={
                'verbose_name': 'مهر فیزیکی',
                'verbose_name_plural': 'مهرهای فیزیکی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='کد محل')),
                ('name', models.CharField(max_length=100, verbose_name='نام محل روی لباس')),
                ('location_type', models.CharField(choices=[('front', 'جلو'), ('back', 'پشت'), ('sleeve_left', 'آستین چپ'), ('sleeve_right', 'آستین راست'), ('pocket', 'جیب'), ('collar', 'یقه'), ('rakab', 'رکب'), ('cuff', 'سر آستین'), ('hem', 'دامن')], max_length=20, verbose_name='نوع محل')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ضریب قیمت')),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='حداکثر عرض (سانتی\u200cمتر)')),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='حداکثر ارتفاع (سانتی\u200cمتر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'محل چاپ',
                'verbose_name_plural': 'محل\u200cهای چاپ',
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام قالب')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('preview_image', models.ImageField(upload_to='templates/previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('thumbnail', models.ImageField(upload_to='templates/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(related_name='design_templates', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('print_locations', models.ManyToManyField(related_name='design_templates', to='designs.printlocation', verbose_name='محل\u200cهای چاپ')),
                ('tags', models.ManyToManyField(related_name='design_templates', to='designs.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'قالب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StampRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=50, verbose_name='وضعیت')),
                ('size', models.CharField(max_length=100, verbose_name='اندازه مهر')),
                ('material', models.CharField(max_length=100, verbose_name='جنس مهر')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='مهلت تحویل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_requests', to='business.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_requests', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_requests', to='designs.design', verbose_name='طرح')),
                ('physical_stamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stamp_requests', to='designs.physicalstamp', verbose_name='مهر فیزیکی')),
            ],
            options={
                'verbose_name': 'درخواست مهر',
                'verbose_name_plural': 'درخواست\u200cهای مهر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyDesignRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_type', models.CharField(max_length=100, verbose_name='نوع طرح')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_required', models.BooleanField(default=True, verbose_name='ضروری است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requirements', to='designs.family', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'نیاز طراحی خانواده',
                'verbose_name_plural': 'نیازهای طراحی خانواده\u200cها',
                'ordering': ['family', 'design_type'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='families', to='designs.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='design',
            name='categories',
            field=models.ManyToManyField(related_name='designs', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AddField(
            model_name='design',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_designs', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='design',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL, verbose_name='طراح'),
        ),
        migrations.AddField(
            model_name='design',
            name='similar_designs',
            field=models.ManyToManyField(blank=True, related_name='related_designs', to='designs.design', verbose_name='طرح\u200cهای مشابه'),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(related_name='designs', to='designs.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='DesignFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='موقعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_families', to='designs.design', verbose_name='طرح')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_families', to='designs.family', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'طرح-خانواده',
                'verbose_name_plural': 'طرح\u200cهای-خانواده\u200cها',
                'ordering': ['family', 'position'],
                'unique_together': {('design', 'family')},
            },
        ),
    ]
