# Generated by Django 4.2 on 2025-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/images/', verbose_name='تصویر محصول'),
        ),
        migrations.AddField(
            model_name='design',
            name='raster_file',
            field=models.ImageField(blank=True, null=True, upload_to='designs/raster/', verbose_name='فایل تصویری'),
        ),
        migrations.AddField(
            model_name='design',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/svg/', verbose_name='فایل وکتور'),
        ),
        migrations.AddField(
            model_name='design',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='designs/thumbnails/', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AlterField(
            model_name='design',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='design',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
