# Generated by Django 4.2 on 2025-06-04 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='کد محل')),
                ('name', models.CharField(max_length=100, verbose_name='نام محل روی لباس')),
                ('location_type', models.CharField(choices=[('front', 'جلو'), ('back', 'پشت'), ('sleeve_left', 'آستین چپ'), ('sleeve_right', 'آستین راست'), ('pocket', 'جیب'), ('collar', 'یقه'), ('rakab', 'رکب'), ('cuff', 'سر آستین'), ('hem', 'دامن')], max_length=20, verbose_name='نوع محل')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='ضریب قیمت')),
                ('max_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='حداکثر عرض (سانتی\u200cمتر)')),
                ('max_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='حداکثر ارتفاع (سانتی\u200cمتر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'محل چاپ',
                'verbose_name_plural': 'محل\u200cهای چاپ',
                'ordering': ['location_type', 'name'],
            },
        ),
    ]
