# Generated by Django 4.2 on 2025-06-09 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_printlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='file',
        ),
        migrations.RemoveField(
            model_name='design',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='design',
            name='design_type',
            field=models.CharField(choices=[('flower', 'گل'), ('pattern', 'نقش'), ('text', 'متن'), ('logo', 'لوگو'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع طرح'),
        ),
        migrations.AddField(
            model_name='design',
            name='file_type',
            field=models.CharField(choices=[('vector', 'وکتور'), ('image', 'عکس'), ('mixed', 'ترکیبی')], default='vector', max_length=20, verbose_name='نوع فایل'),
        ),
        migrations.AddField(
            model_name='design',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع (پیکسل)'),
        ),
        migrations.AddField(
            model_name='design',
            name='laser_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/laser/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dxf', 'ai', 'eps'])], verbose_name='فایل لیزری'),
        ),
        migrations.AddField(
            model_name='design',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/products/', verbose_name='عکس محصول'),
        ),
        migrations.AddField(
            model_name='design',
            name='similar_designs',
            field=models.ManyToManyField(blank=True, related_name='related_designs', to='designs.design', verbose_name='طرح\u200cهای مشابه'),
        ),
        migrations.AddField(
            model_name='design',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/svg/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='فایل وکتور'),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(related_name='designs', to='designs.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='design',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/', verbose_name='تصویر بندانگشتی'),
        ),
        migrations.AddField(
            model_name='design',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض (پیکسل)'),
        ),
        migrations.AddField(
            model_name='family',
            name='exclusive_design_types',
            field=models.JSONField(default=list, help_text='انواع طرح\u200cهایی که فقط مختص این خانواده هستند', verbose_name='انواع طرح\u200cهای انحصاری'),
        ),
        migrations.AddField(
            model_name='family',
            name='required_design_types',
            field=models.JSONField(default=dict, help_text='نوع و تعداد طرح\u200cهای مورد نیاز برای این خانواده', verbose_name='نیازمندی\u200cهای طرح'),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت (ریال)'),
        ),
    ]
