# Generated by Django 4.2 on 2025-06-09 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_remove_design_file_remove_design_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام قالب')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('preview_image', models.ImageField(upload_to='templates/previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('thumbnail', models.ImageField(upload_to='templates/thumbnails/', verbose_name='تصویر بندانگشتی')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(related_name='design_templates', to='designs.designcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('print_locations', models.ManyToManyField(related_name='design_templates', to='designs.printlocation', verbose_name='محل\u200cهای چاپ')),
                ('tags', models.ManyToManyField(related_name='design_templates', to='designs.tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'قالب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
