# Generated by Django 4.2 on 2025-05-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='نسخه')),
                ('file', models.FileField(upload_to='sets/', verbose_name='فایل خروجی')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='sets/previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار ست\u200cبند'), ('in_progress', 'در حال ست\u200cبندی'), ('pending_approval', 'منتظر تأیید مشتری/چاپخانه'), ('rejected', 'رد شده'), ('completed', 'تأیید و تکمیل')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ست\u200cبندی (ریال)')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('designer', models.ForeignKey(blank=True, limit_choices_to={'roles__contains': 'set_designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_setjobs', to=settings.AUTH_USER_MODEL, verbose_name='ست\u200cبند')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_designs', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='set_design.setdesign', verbose_name='ست والد (برای نسخه\u200cبندی)')),
            ],
            options={
                'verbose_name': 'ست\u200cبندی',
                'verbose_name_plural': 'ست\u200cبندی\u200cها',
                'ordering': ('-created_at',),
                'unique_together': {('order_item', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SetDesignRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('assigned', 'اختصاص داده شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'کم'), (2, 'متوسط'), (3, 'زیاد'), (4, 'فوری')], default=2, verbose_name='اولویت')),
                ('requirements', models.TextField(verbose_name='نیازمندی\u200cها')),
                ('deadline', models.DateTimeField(verbose_name='مهلت انجام')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_set_designs', to=settings.AUTH_USER_MODEL, verbose_name='طراح')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_design_requests', to='orders.order', verbose_name='سفارش')),
                ('reference_images', models.ManyToManyField(blank=True, related_name='reference_for_sets', to='designs.design', verbose_name='تصاویر مرجع')),
                ('result_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='set_design.setdesign', verbose_name='ست نهایی')),
            ],
            options={
                'verbose_name': 'درخواست ست\u200cبندی',
                'verbose_name_plural': 'درخواست\u200cهای ست\u200cبندی',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
