# Generated by Django 4.2 on 2025-06-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('set_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdesign',
            name='actual_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان واقعی تکمیل'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_set_designs_active', to=settings.AUTH_USER_MODEL, verbose_name='مسئول ست\u200cبندی'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='auto_notification',
            field=models.BooleanField(default=True, verbose_name='اطلاع\u200cرسانی خودکار'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='complexity_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='سطح پیچیدگی'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تخمینی تکمیل'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='revision_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای اصلاح'),
        ),
        migrations.AddField(
            model_name='setdesign',
            name='source_files',
            field=models.JSONField(blank=True, default=list, help_text='لیست فایل\u200cهای اصلی طرح\u200cها', verbose_name='فایل\u200cهای منبع'),
        ),
        migrations.AlterField(
            model_name='setdesign',
            name='designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__name': 'set_designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_setjobs', to=settings.AUTH_USER_MODEL, verbose_name='ست\u200cبند'),
        ),
        migrations.AlterField(
            model_name='setdesign',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار ست\u200cبند'), ('assigned', 'اختصاص داده شده'), ('in_progress', 'در حال ست\u200cبندی'), ('pending_approval', 'منتظر تأیید مشتری/چاپخانه'), ('revision_needed', 'نیاز به اصلاح'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('completed', 'تأیید و تکمیل')], default='waiting', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='setdesignrequest',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_set_design_requests', to=settings.AUTH_USER_MODEL, verbose_name='طراح'),
        ),
    ]
