# Generated by Django 4.2 on 2025-05-03 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام بخش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('max_width', models.PositiveIntegerField(verbose_name='حداکثر عرض (سانتی\u200cمتر)')),
                ('max_height', models.PositiveIntegerField(verbose_name='حداکثر ارتفاع (سانتی\u200cمتر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('supports_digital', models.BooleanField(default=True, verbose_name='پشتیبانی از چاپ دیجیتال')),
                ('supports_manual', models.BooleanField(default=True, verbose_name='پشتیبانی از چاپ دستی')),
                ('min_dpi', models.PositiveIntegerField(default=300, verbose_name='حداقل DPI تصویر')),
            ],
            options={
                'verbose_name': 'بخش لباس',
                'verbose_name_plural': 'بخش\u200cهای لباس',
                'ordering': ['name'],
            },
        ),
    ]
