# Generated by Django 4.2 on 2025-06-11 07:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('opening_hours', models.CharField(blank=True, max_length=200, verbose_name='ساعت کاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='شخص رابط')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'مکان چاپ',
                'verbose_name_plural': 'مکان\u200cهای چاپ',
                'ordering': ['city', 'name'],
            },
        ),
    ]
