# Generated by Django 4.2 on 2025-05-03 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گزارش',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گزارش',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('type', models.CharField(choices=[('sales', 'فروش'), ('profit', 'سود'), ('user_activity', 'فعالیت کاربر'), ('business_performance', 'عملکرد کسب\u200cوکار')], max_length=20, verbose_name='نوع گزارش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('data', models.JSONField(verbose_name='داده\u200cهای گزارش')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='business.business', verbose_name='کسب\u200cوکار')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reportcategory', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-generated_at'],
            },
        ),
    ]
