# Generated by Django 4.2 on 2025-05-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام کسب\u200cوکار')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, upload_to='business/logos/', verbose_name='لوگو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'فعالیت کسب\u200cوکار',
                'verbose_name_plural': 'فعالیت\u200cهای کسب\u200cوکار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business.business', verbose_name='کسب\u200cوکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر کسب\u200cوکار',
                'verbose_name_plural': 'کاربران کسب\u200cوکار',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
