# Generated by Django 4.2 on 2025-06-11 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کسب\u200cوکار')),
                ('type', models.CharField(blank=True, choices=[('manual_print', 'چاپ دستی'), ('digital_print', 'چاپ دیجیتال'), ('laser', 'حکاکی لیزری'), ('delivery', 'تحویل\u200cگیرنده'), ('set_design', 'ست\u200cبندی')], max_length=50, null=True, verbose_name='نوع کسب\u200cوکار')),
                ('services', models.JSONField(blank=True, null=True, verbose_name='خدمات')),
                ('allow_customer_info', models.BooleanField(default=False, verbose_name='اجازه دسترسی به اطلاعات مشتری')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='نقش')),
                ('payment_type', models.CharField(choices=[('percentage', 'درصدی'), ('monthly', 'ماهیانه')], max_length=20, verbose_name='نوع پرداخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='business.business', verbose_name='کسب\u200cوکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقش کارمند',
                'verbose_name_plural': 'نقش\u200cهای کارمند',
            },
        ),
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فعالیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('activity_type', models.CharField(choices=[('design_sale', 'فروش طرح'), ('design_purchase', 'خرید طرح'), ('order_created', 'ایجاد سفارش'), ('order_completed', 'تکمیل سفارش'), ('payment_received', 'دریافت پرداخت'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع فعالیت')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='جزئیات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'فعالیت کسب\u200cوکار',
                'verbose_name_plural': 'فعالیت\u200cهای کسب\u200cوکار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='businesses', through='business.EmployeeRole', to=settings.AUTH_USER_MODEL, verbose_name='کارمندان'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_users', to='business.business', verbose_name='کسب\u200cوکار')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر کسب\u200cوکار',
                'verbose_name_plural': 'کاربران کسب\u200cوکار',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'user')},
            },
        ),
    ]
