# Generated by Django 4.2 on 2025-05-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessactivity',
            name='activity_type',
            field=models.CharField(choices=[('design_sale', 'فروش طرح'), ('design_purchase', 'خرید طرح'), ('order_created', 'ایجاد سفارش'), ('order_completed', 'تکمیل سفارش'), ('payment_received', 'دریافت پرداخت'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع فعالیت'),
        ),
        migrations.AddField(
            model_name='businessactivity',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='جزئیات'),
        ),
    ]
