# Generated by Django 4.2 on 2025-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='type',
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('print', 'چاپ'), ('laser', 'حکاکی لیزری'), ('set_design', 'ست\u200cبندی'), ('delivery', 'تحویل')], default='print', max_length=20, verbose_name='نوع کسب\u200cوکار'),
        ),
    ]
