# Generated by Django 4.2 on 2025-06-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بخش')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد بخش')),
                ('default_price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ضریب قیمت')),
            ],
            options={
                'verbose_name': 'بخش لباس',
                'verbose_name_plural': 'بخش\u200cهای لباس',
            },
        ),
    ]
