# Generated by Django 4.2 on 2025-05-15 05:46

import apps.templates_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('featured', 'Featured'), ('archived', 'Archived')], default=apps.templates_app.models.Template.Status['DRAFT'], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_templates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
